name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # This ensures the use of a personal access token (PAT) for pushing changes
        fetch-depth: 0 # This fetches the full history necessary for commits

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Maven 3.9.2
      run: |
        MAVEN_VERSION=3.9.2
        wget https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
        tar -xvzf apache-maven-$MAVEN_VERSION-bin.tar.gz
        sudo mv apache-maven-$MAVEN_VERSION /opt/maven
        if [ -L /usr/bin/mvn ]; then sudo rm /usr/bin/mvn; fi
        sudo ln -s /opt/maven/bin/mvn /usr/bin/mvn
        mvn -v

    - name: Increment patch version
      id: version
      run: |
        VERSION_FILE="version.txt"
        if [ ! -f $VERSION_FILE ]; then
          echo "1.0.0" > $VERSION_FILE
        fi
        CURRENT_VERSION=$(cat $VERSION_FILE)
        PATCH=$(echo $CURRENT_VERSION | awk -F. '{print $3}')
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v new_patch=$NEW_PATCH '{print $1 "." $2 "." new_patch}')
        echo $NEW_VERSION > $VERSION_FILE
        echo "New version: $NEW_VERSION"
        echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Commit and push new version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add version.txt
        git commit -m "Increment version to ${{ env.VERSION }}"
        git push origin HEAD:master

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:${{ env.VERSION }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:${{ env.VERSION }}
